name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:
		
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: npm

      - name: Build
        run: |
          npm ci
          npm set-script build "next build"
          npm set-script export "next export"
          touch out/.nojekyll

      - name: Deploy
        # configure an external GitHub Pages deploy workflow here
        uses: JamesIves/github-pages-deploy-action@4.4.0 
        with:
          branch: gh-pages
          folder: out
